### ISSUE TITLE
Forgotten console statement

### ISSUE THREAD

**Issue by aelyseev** [kalashnikovisme/nano-metadata#3]
https://github.com/kalashnikovisme/nano-metadata/blob/develop/lib/video/duration.js#L7

**Comment by kalashnikovisme** [comment]
left it, because of this thread :) https://twitter.com/kalashnikovisme/status/1581280233000689666

But you're right, it's time to remove it.

**Comment by kalashnikovisme** [comment]
New release [0.1.1](https://github.com/kalashnikovisme/nano-metadata/releases/tag/0.1.1) is ready
